### ISSUE TITLE
Bug/Error with the _super property in latest version

### ISSUE THREAD

**Issue by josefanostylus** [Olical/Heir#10]
I found a bug when using the _super property inside a subclass. Please check the fiddle provided below
I used the same code as in your demo. 

"Uncaught TypeError: Cannot read property 'foo' of undefined
    at Sub.foo ((index)..."

I believe this error is due to this line :  

    destination._super = source.prototype

If changed to 

    destination.prototype._super = source.prototype

then it will work.

## Version
v3.0.0

## Test Case
https://jsfiddle.net/josefano09/w81xdg45/1/

## Steps to reproduce
Use heir.inherit(Sub, Base); and then inside the Sub class try to call this._super. The above error will show in the console.

**Comment by Olical** [comment]
Wow, this is an old project of mine :sweat_smile: thanks for the detailed report though, I'll take a look.

**Comment by Olical** [comment]
Ah! It's a documentation issue! It shouldn't be `this._super` any more. It should be `Sub._super`, it's a static property on the current class, not `this`. It was changed because there was a way to get into an infinite loop otherwise. I'm cleaning the docs up now though.
